name: tubesmopro
description: "APLIKASI KESEHATAN KAMPUS"

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^2.0.15 #depedencies ara clear sesi
  url_launcher: ^6.0.20 #depedencies terpakai haikal
  cupertino_icons: ^1.0.8
  
  # State Management
  provider: ^6.1.1
  
  # UI Components
  google_fonts: ^6.1.0  #depedencies terpakai fadlan
  flutter_svg: ^2.0.9
  cached_network_image: ^3.3.1 #depedencies terpakai fachry
  shimmer: ^3.0.0 #depedencies terpakai naufal

  # Database & Storage
  sqflite: ^2.3.0
  path_provider: ^2.1.2
  
  # Network & API
  dio: ^5.4.0
  connectivity_plus: ^5.0.2 #depedencies terpakai fadlan tes koneksi internet di homepage
  
  # Utility
  intl: ^0.19.0 #depedencies terpakai ihsan
  share_plus: ^7.2.1 #depedencies terpakai haikal
  like_button: ^2.0.5 #depedencies terpakai ihsan
  elegant_notification: ^2.3.0 #depedencies terpakai fachry
  flutter_local_notifications: ^17.2.4 #depedencies terpakai fachry
  flutter_timezone: ^3.0.1 #depedencies terpakai fachry
  rxdart: ^0.28.0 #depedencies terpakai fachry



dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/image/